openapi: 3.1.0
info:
  title: Flutter Push API
  version: 1.0.0
  description: An API to push Flutter code to a GitHub repository
servers:
  - url: https://flutter-build-demo.vercel.app/api
paths:
  /push:
    post:
      summary: Push Flutter code to GitHub
      operationId: pushCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: Dart source code to push
      responses:
        '200':
          description: Code pushed successfully
        '400':
          description: Bad input
        '500':
          description: GitHub error
