name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - run: flutter pub get

      # Build Web App
      - run: flutter build web --release
      
      # Build Android APK (can add iOS similarly if you want)
      - run: flutter build apk --release

      # List output files for debugging
      - run: ls build/web
      - run: ls build/app/outputs/flutter-apk/

      # Upload web build as artifact
      - uses: actions/upload-artifact@v4
        with:
          name: flutter-web-build
          path: build/web

      # Upload APK build as artifact
      - uses: actions/upload-artifact@v4
        with:
          name: flutter-apk-build
          path: build/app/outputs/flutter-apk/app-release.apk
