name: Flutter Web Build & Copy to Root

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web (default output to build/web)
        run: flutter build web --release

      - name: Copy build output to root
        run: |
          cp -r build/web/* .

      - name: Commit and push copied build files
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update root with latest Flutter web build" || echo "Nothing to commit"
          git push origin HEAD
